### ISSUE TITLE
Problems building with Node v6.1.0 (Current)

### ISSUE THREAD

**Issue by manwithacat** [angular-university/courses#1]
Hi,

I'm seeing a problem with the `npm start` script. The individual scripts (`build-ts`,`build-lib`, and `serve`) all seem to work fine, but it's choking on the definition of `npm-run-all`, which is a devDependency not a script.

Log file:
[npm-debug.log.txt](https://github.com/angular-academy/courses/files/264083/npm-debug.log.txt)

**Comment by angular-academy-devs** [comment]
Hello, and did you give it a try with the latest node 4 ? its the stable release - Long Term Support. You will in general run into less issues because its more stable. 

Try putting ./node_modules/.bin in the path: 

```
"start": "./node_modules/.bin/npm-run-all build-ts build-lib  -p watch serve "
```

Does any of those two things fix it ?

**Comment by manwithacat** [comment]
This is fun. The Windows command interpreter doesn't like the space at the start of the `watch` script definition in `package.json`. If you remove that, everything is fine

``` bat
"watch": " ./node_modules/.bin/nodemon -V -w src --ext \".ts\" --exec \"npm run build-ts\"",
```

versus

``` bat
"watch": "./node_modules/.bin/nodemon -V -w src --ext \".ts\" --exec \"npm run build-ts\"",
```

Works with LTS and Current. No path changes required.

**Comment by angular-academy-devs** [comment]
Definitively looked like some sort of tooling bug. Fixed, thank you for the solution.
