### ISSUE TITLE
Issue while starting the server

### ISSUE THREAD

**Issue by guntgatti** [angular-university/courses#5]
Hello,
The clean and the start commands are chained in package.json file. 
NPM is not recognizing the below line in start script.
npm run clean && ./node_modules/.bin/ts-node lessons-server.ts 
(logical anding viz. && of npm specific command with native command ), hence the native command has to be mapped to a different task. 
Hence I have made the following changes in my package.json file.
"scripts": {
    "clean": "./node_modules/.bin/rimraf dist",
    "start-server": "./node_modules/.bin/ts-node lessons-server.ts",
    "start": "npm run clean && npm run start-server"
  }
After changing this, "npm run start" or "npm start" works fine.

**Comment by jhades** [comment]
Hello @guntgatti , thank you for reporting, I have just now fixed this.
